INSERT INTO Shelter (name, address) VALUES
('Kittery Animal Hospital and Creature Comforts LLC', '195 State Road'),
('Lilac Groves Pampered Pups', '94 Grove Road'),
('Northern New England Westie Rescue Inc', NULL),
('NHSPCA', '104 Portsmouth Avenue'),
('The Grateful Dog Animal Rescue', NULL),
('Cats 1st', '4 Baker St'),
('Cocheco Valley Humane Society', '262 County Farm Road'),
('4 Lil Paws Ferret Shelter', NULL),
('All Breed Rescue and Adoption Inc.', NULL),
('Merrimack River Feline Rescue Society', '63 Elm St.'),
('Emma''s Angels Rescue', NULL),
('FuRRR Feline Rescue, Rehabilitation and Retirement', '10 Main St. Unit 99'),
('Safe Tails Animal Rescue', NULL),
('Safe Haven Humane Society', '1420 Post Road'),
('New England Equine Rescue North', '52 Ash St'),
('PRONE - Papillon Rescue of the North East', NULL),
('One Tail at a Time Rescue, Inc.', NULL),
('Cairn Rescue League', NULL),
('Alpha Dog Rescue', NULL),
('Mary''s Dogs', NULL),
('Lucky Pup Rescue', NULL),
('Ipswich Humane Group Inc.', '17 Fowlers Lane'),
('Voice for Animals', NULL),
('Greater Derry Humane Society Inc.', 'P. O. Box 142'),
('Feline Friends', 'PO Box 2452'),
('Salem Animal Rescue League', '4 Sari Dr'),
('MSPCA at Nevins Farm', '400 Broadway'),
('Odd Dog Rescue', '69 Forest Street'),
('Cape Ann Animal Aid', '4 Paws Lane'),
('Greyhound Pets of America - Central NH Chapter', 'PO Box 305'),
('Great Dog Rescue New England', NULL),
('Live and Let Live Farm', '20 Paradise Lane'),
('Homes for Happy Dogs, Inc.', '109 Dover Rd'),
('Animal Allies', 'P.O. Box 693'),
('North East Afghan Hound Rescue, Inc', NULL),
('All Better Pets', '55 Carl Drive'),
('Darbster Foundation', '332 Kelley St'),
('Friends of Beverly Animals', 'PO Box 3378'),
('Lucky Mutt Animal Rescue', NULL),
('Hope Harbor Animal Society', NULL),
('Animal Rescue Network of New England', 'P.O. Box 1053'),
('Friends of the Manchester Animal Shelter', '490 Dunbarton Road'),
('For Dog''s Sake', NULL),
('Animal Umbrella Inc.', '150 (R) Main St'),
('Northeast Animal Shelter', '347 Highland Ave'),
('PALS Animal Life Savers', '10 Traders Way'),
('The Odd Cat Sanctuary', 'PO Box 405'),
('Animal Rescue League of New Hampshire', '545 Route 101'),
('Blind Dog Rescue Alliance - MA', 'PO Box 63401'),
('Friends of Marblehead''s Abandoned Animals', '44 Village St.');